# Generated by Django 5.0.2 on 2024-02-08 19:17

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_class',
            field=models.CharField(max_length=4, validators=[users.validators.validate_class]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, validators=[users.validators.validate_phone]),
        ),
    ]
